import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    home: "Home",
    features: "Features",
    queueStatus: "Queue Status",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    bookings: "Bookings",
    vipManagement: "VIP Management",
    capacityManagement: "Capacity Management",
    staffManagement: "Staff Management",
    settings: "Settings",
    help: "Support",
    newEntry: "New Entry",
    qrScanner: "QR Scanner",
    parkingManagement: "Parking Management",
    reportsAnalytics: "Reports & Analytics",
    userManagement: "User Management",
    announcements: "Announcements",
    festivalManagement: "Festival Management",
    notifications: "Notifications",
    profile: "Profile",
    myPass: "My Pass",

    // Homepage
    heroTitle: "Experience the Divine Without the Wait",
    heroSubtitle: "Skip long queues with digital booking, QR verification, and real-time queue tracking. Experience a seamless spiritual journey with our modern administrative technology.",
    bookDarshan: "Book Darshan",
    checkQueue: "Check Queue Status",
    featuresTitle: "Streamlined Temple Access",
    featuresSub: "Everything you need for a peaceful and organized temple visit in one professional platform.",
    onlineBooking: "Online Booking",
    onlineBookingDesc: "Schedule your visit in advance and pick a time slot that suits your convenience.",
    qrToken: "QR Token",
    qrTokenDesc: "Instant digital passes with unique QR codes for rapid, contactless gate entry.",
    liveTracking: "Live Queue Tracking",
    liveTrackingDesc: "Monitor wait times and queue positions in real-time from your mobile device.",
    vipMgt: "VIP Management",
    vipMgtDesc: "Special fast-track arrangements for senior citizens and differently-abled devotees.",
    mobileFriendly: "Mobile Friendly",
    mobileFriendlyDesc: "Responsive interface designed for effortless access on all smartphone devices.",
    realTimeUpdates: "Real-Time Updates",
    realTimeUpdatesDesc: "Receive SMS and app alerts about festival timings and administrative changes.",
    announcementsTitle: "Announcements & Notices",
    officialPortal: "Official Smart Darshan Portal",
    verifyAtGate: "Verify at Gate",
    slot: "Slot",
    noticeBoard: "Temple Notice Board",
    noticeSubtitle: "Stay updated with the latest festival schedules and administrative announcements.",
    viewAllNotices: "View All Notices",
    readDetails: "Read Details",
    watchLive: "Watch Live",
    donateNow: "Donate Now",
    newTag: "New",
    updateTag: "Update",
    adminTag: "Admin",
    notice1Title: "Maha Shivratri Special Timings",
    notice1Desc: "Temple will remain open throughout the night for special prayers and Abhishekam ceremonies.",
    notice2Title: "Live Stream for Morning Aarti",
    notice2Desc: "Experience the divine energy from home. Live streaming starts daily at 5:30 AM on our portal.",
    notice3Title: "Annadanam Donation Portal",
    notice3Desc: "We have launched a simplified portal for sponsoring meals for devotees. Contribute now.",

    // User Dashboard
    welcomeUser: "Welcome back",
    darshanDate: "Darshan Date: Oct 24, 2026",
    currentStatus: "Current Status: Confirmed",
    digitalPass: "Digital Darshan Pass",
    devoteeName: "Devotee Name",
    tokenId: "Token ID",
    mobile: "Mobile",
    persons: "Persons",
    reportingTime: "Reporting Time",
    viewPass: "View Pass",
    downloadPass: "Download Pass",
    entranceGate: "Scan at Entrance Gate 3",
    liveQueue: "Live Queue",
    currentToken: "Current Token",
    yourToken: "Your Token",
    queueProgress: "Queue Progress",
    complete: "Complete",
    estWait: "Est. Wait",
    mins: "Mins",
    queuePosition: "Queue Position",
    away: "away",
    timingsTitle: "Darshan Timings",
    noticesTitle: "Festival Notices",
    assistance: "Need Assistance?",
    assistanceDesc: "Our dedicated volunteer team is here to help you with your spiritual journey.",

    // Committee Member
    committeeTitle: "Committee Member Dashboard",
    totalToday: "Total Today",
    currentlyInside: "Currently Inside",
    avgWaitTime: "Avg. Wait Time",
    currentlyServing: "Currently Serving",
    skip: "Skip",
    nextToken: "Next Token",
    pause: "Pause",
    resume: "Resume",
    vipPriorityPool: "VIP Priority Pool",
    waitlistItems: "Waitlist Items",

    // Admin Dashboard
    welcomeAdmin: "Welcome Admin",
    liveSystemStatus: "Live System Status",
    totalBookingsToday: "Total Bookings Today",
    totalVisitorsToday: "Total Visitors Today",
    visitorsInside: "Visitors Inside Temple",
    queueCount: "Queue Count",
    vipVisitors: "VIP Visitors Today",
    parkingOccupancy: "Parking Occupancy",
    completedDarshans: "Completed Darshans",
    cancelledBookings: "Cancelled Bookings",
    liveQueueOverview: "Live Queue Overview",
    bookingAnalytics: "Booking Analytics",
    recentActivities: "Recent Activities",
    upcomingFestival: "Upcoming Festival",
    quickActions: "Quick Actions",
    notificationCenter: "Notification Center",
    capacityControls: "Temple Capacity Controls",
    overrideLimit: "Override Limit",
    dailyVisitorLimit: "Daily Visitor Limit",
    emergencyClosure: "Emergency Closure Protocol",
    liftEmergency: "Lift Emergency Closure",

    // Forms & Alerts
    nameLabel: "Devotee Name",
    categoryLabel: "Category",
    queueTypeLabel: "Queue Type",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    confirmLogout: "Are you sure you want to log out?",

    // Capacity Management
    capacityMgmtTitle: "Capacity Management",
    capacityMgmtSubtitle: "Manage daily booking limits, visitor thresholds, and real-time slot availability.",
    exportReport: "Export Report",
    totalDailyCapacity: "Total Daily Capacity",
    availableSlots: "Available Slots",
    capacityUtilization: "Capacity Utilization",
    liveCapacityStatus: "Live Capacity Status",
    onlineBooked: "Online Booked",
    walkins: "Walk-ins",
    online: "Online",
    cancelled: "Cancelled",
    vipSpecial: "VIP/Special",
    capacityConfiguration: "Capacity Configuration",
    maxVisitorsPerDay: "Maximum Visitors Per Day",
    maxVehiclesPerDay: "Maximum Vehicles Per Day",
    maxPersonsPerBooking: "Maximum Persons Per Booking",
    resetToDefaults: "Reset to Defaults",
    currentStatus: "Current Status",
    openForBooking: "Open for Booking",
    bookingsStopped: "Bookings Stopped",
    bookingRate: "Booking Rate",
    stop: "Stop",
    systemAlerts: "System Alerts",
    limitOverridden: "Override Limit",
    refreshingIn: "Refreshing in",
    utilized: "Utilized",

    // Parking Management
    parkingMgmtTitle: "Parking Management",
    parkingMgmtSubtitle: "Manage vehicle parking, occupancy, and visitor vehicle records.",
    shiftMorning: "Shift: Morning",
    totalCapacity: "Total Capacity",
    occupiedSlots: "Occupied Slots",
    vehiclesToday: "Vehicles Today",
    vehicleEntryForm: "Vehicle Entry Form",
    vehicleNumber: "Vehicle Number",
    vehicleType: "Vehicle Type",
    twoWheeler: "Two Wheeler",
    fourWheeler: "Four Wheeler",
    bus: "Bus",
    vip: "VIP",
    driverName: "Driver Name",
    mobileNumber: "Mobile Number",
    tokenNumber: "Token Number",
    assignParkingSlot: "Assign Parking Slot",
    parkingSlotStatus: "Parking Slot Status",
    available: "Available",
    occupied: "Occupied",
    disabled: "Disabled",
    quickSearch: "Quick Search",
    markVehicleExit: "Mark Vehicle Exit",
    peakHourCapacity: "Peak Hour Capacity",
    morningPeak: "Morning (6AM - 10AM)",
    middayPeak: "Midday (11AM - 3PM)",
    eveningPeak: "Evening (4PM - 9PM)",
    recentVehicleEntries: "Recent Vehicle Entries",
    viewAllEntries: "View All Entries",
    parked: "Parked",
    exited: "Exited",

    // Scanner
    qrScannerTitle: "QR Scanner & Visitor Verification",
    qrScannerSubtitle: "Scan devotee QR codes for instant darshan verification and real-time entry tracking.",
    liveScanner: "Live Scanner",
    cameraActive: "Camera Active",
    scanQrCode: "Scan QR Code",
    manualSearch: "Manual Search",
    familyPass: "Family Pass",
    bookingTime: "Booking Time",
    phone: "Phone",
    vehicle: "Vehicle",
    members: "Members",
    gateNo: "Gate No.",
    verifyEntry: "Verify Entry",
    markInQueue: "Mark In Queue",
    markEntered: "Darshan Completed",
    insideTemple: "Inside Temple",
    pending: "Pending",
    recentScans: "Recent Scans",
    viewAll: "View All",
    verified: "Verified",
    waiting: "Waiting",

    // Offline Verification
    offlineVerificationTitle: "Offline Visitor Verification",
    offlineVerificationSubtitle: "Register and verify walk-in devotees without online bookings.",
    searchVisitor: "Search Visitor",
    mobileOrToken: "Mobile or Token Number",
    search: "Search",
    offlineVisitorForm: "Offline Visitor Entry Form",
    fullName: "Full Name *",
    mobileNumberRequired: "Mobile Number *",
    placeVillage: "Place/City/Village",
    numberOfPersons: "Number of Persons *",
    darshanDateLabel: "Darshan Date",
    generateToken: "Generate Token",
    recentOfflineEntries: "Recent Offline Entries",
    visitorName: "Visitor Name",
    entryTime: "Entry Time",
    currentGeneratedToken: "Current Generated Token",
    markEnteredTemple: "Mark Entered Temple",
    printToken: "Print Token",
    dailyStatistics: "Daily Statistics",
    offlineVisitors: "Offline Visitors",
    totalPersons: "Total Persons",
    activeQueue: "Active Queue",
    completed: "Completed",
    registrationConfirmed: "Registration Confirmed!",
    tokenId: "Token ID",
    printPass: "Print Pass",
    downloadPass: "Download Pass",
    scanAtEntrance: "Scan at Entrance",
    viewPassDetails: "View Pass Details",
    generateNewEntry: "Generate New Entry",

    // Analytics
    analyticsTitle: "Analytics & Reports",
    analyticsSubtitle: "Real-time insights and devotional traffic management.",
    last24Hours: "Last 24 Hours",
    dailyVisitorTrends: "Daily Visitor Trends",
    crowdCapacity: "Crowd Capacity",
    optimal: "Optimal",
    peopleOnsite: "People On-site",
    recommendedLimit: "Recommended limit",
    vehicleEntry: "Vehicle Entry",
    twoWheelers: "Two-Wheelers",
    fourWheelers: "Four-Wheelers",
    largeVehicles: "Large Vehicles",
    liveEntryCount: "Live Entry Count",
    totalMale: "Total Male",
    totalFemale: "Total Female",
    avgDwellTime: "Avg. Dwell Time",
    slotManagement: "Slot Management",
    modifyVisitorLimits: "Modify visitor limits or initiate protocol closure.",
    emergencyClosureTitle: "EMERGENCY CLOSURE",
    closureActive: "CLOSURE ACTIVE",
    auditLogs: "Audit Logs",
    viewAllActivity: "View All Activity",
    hourlyEntryStats: "Hourly Entry Statistics",
    table: "Table",
    heatmap: "Heatmap",
    hourSlot: "Hour Slot",
    totalVisitors: "Total Visitors",
    vehicles: "Vehicles",
    waitTime: "Wait Time"
  },
  hi: {
    // Navigation
    home: "मुख्य पृष्ठ",
    features: "विशेषताएं",
    queueStatus: "कतार की स्थिति",
    contact: "संपर्क",
    login: "लॉगिन",
    logout: "लॉगआउट",
    dashboard: "डैशबोर्ड",
    bookings: "बुकिंग",
    vipManagement: "वीआईपी प्रबंधन",
    capacityManagement: "क्षमता प्रबंधन",
    staffManagement: "कर्मचारी प्रबंधन",
    settings: "सेटिंग्स",
    help: "सहायता",
    newEntry: "नई प्रविष्टि",
    qrScanner: "क्यूआर स्कैनर",
    parkingManagement: "पार्किंग प्रबंधन",
    reportsAnalytics: "रिपोर्ट और विश्लेषण",
    userManagement: "उपयोगकर्ता प्रबंधन",
    announcements: "घोषणाएँ",
    festivalManagement: "उत्सव प्रबंधन",
    notifications: "सूचनाएँ",
    profile: "प्रोफ़ाइल",
    myPass: "मेरा पास",

    // Homepage
    heroTitle: "बिना प्रतीक्षा के दिव्य दर्शन करें",
    heroSubtitle: "डिजिटल बुकिंग, क्यूआर सत्यापन और वास्तविक समय कतार ट्रैकिंग के साथ लंबी लाइनों से बचें। हमारी आधुनिक प्रशासनिक तकनीक के साथ एक सुगम आध्यात्मिक यात्रा का अनुभव करें।",
    bookDarshan: "दर्शन बुक करें",
    checkQueue: "कतार की स्थिति जांचें",
    featuresTitle: "सुव्यवस्थित मंदिर प्रवेश",
    featuresSub: "एक ही पेशेवर मंच पर शांतिपूर्ण और व्यवस्थित मंदिर दर्शन के लिए आवश्यक सभी चीजें।",
    onlineBooking: "ऑनलाइन बुकिंग",
    onlineBookingDesc: "पहले से अपनी यात्रा का समय निर्धारित करें और अपनी सुविधा के अनुसार समय स्लॉट चुनें।",
    qrToken: "क्यूआर टोकन",
    qrTokenDesc: "त्वरित, संपर्क रहित प्रवेश द्वार के लिए विशिष्ट क्यूआर कोड के साथ तत्काल डिजिटल पास।",
    liveTracking: "लाइव कतार ट्रैकिंग",
    liveTrackingDesc: "अपने मोबाइल डिवाइस से वास्तविक समय में प्रतीक्षा समय और कतार की स्थिति की निगरानी करें।",
    vipMgt: "वीआईपी प्रबंधन",
    vipMgtDesc: "वरिष्ठ नागरिकों और विकलांग श्रद्धालुओं के लिए विशेष त्वरित व्यवस्था।",
    mobileFriendly: "मोबाइल अनुकूल",
    mobileFriendlyDesc: "सभी स्मार्टफोन उपकरणों पर सहज पहुंच के लिए डिज़ाइन किया गया उत्तरदायी इंटरफ़ेस।",
    realTimeUpdates: "वास्तविक समय अपडेट",
    realTimeUpdatesDesc: "त्योहार के समय और प्रशासनिक परिवर्तनों के बारे में एसएमएस और ऐप अलर्ट प्राप्त करें।",
    announcementsTitle: "घोषणाएँ और सूचनाएँ",
    officialPortal: "आधिकारिक स्मार्ट दर्शन पोर्टल",
    verifyAtGate: "प्रवेश द्वार पर सत्यापित करें",
    slot: "समय स्लॉट",
    noticeBoard: "मंदिर सूचना पट्ट",
    noticeSubtitle: "नवीनतम त्योहारों के कार्यक्रम और प्रशासनिक घोषणाओं के साथ अपडेट रहें।",
    viewAllNotices: "सभी सूचनाएं देखें",
    readDetails: "विवरण पढ़ें",
    watchLive: "लाइव देखें",
    donateNow: "अभी दान करें",
    newTag: "नया",
    updateTag: "अपडेट",
    adminTag: "प्रशासन",
    notice1Title: "महा शिवरात्रि विशेष समय",
    notice1Desc: "विशेष पूजा और अभिषेक समारोहों के लिए मंदिर रात भर खुला रहेगा।",
    notice2Title: "सुबह की आरती का लाइव प्रसारण",
    notice2Desc: "घर बैठे दिव्य ऊर्जा का अनुभव करें। हमारे पोर्टल पर प्रतिदिन सुबह 5:30 बजे से लाइव स्ट्रीमिंग शुरू होती है।",
    notice3Title: "अन्नदान दान पोर्टल",
    notice3Desc: "हमने श्रद्धालुओं के लिए भोजन प्रायोजित करने के लिए एक सरल पोर्टल शुरू किया है। अभी योगदान दें।",

    // User Dashboard
    welcomeUser: "वापसी पर स्वागत है",
    darshanDate: "दर्शन तिथि: 24 अक्टूबर, 2026",
    currentStatus: "वर्तमान स्थिति: कन्फर्म",
    digitalPass: "डिजिटल दर्शन पास",
    devoteeName: "श्रद्धालु का नाम",
    tokenId: "टोकन आईडी",
    mobile: "मोबाइल",
    persons: "व्यक्ति",
    reportingTime: "रिपोर्टिंग समय",
    viewPass: "पास देखें",
    downloadPass: "पास डाउनलोड करें",
    entranceGate: "प्रवेश द्वार 3 पर स्कैन करें",
    liveQueue: "लाइव कतार",
    currentToken: "वर्तमान टोकन",
    yourToken: "आपका टोकन",
    queueProgress: "कतार की प्रगति",
    complete: "पूर्ण",
    estWait: "अनुमानित प्रतीक्षा",
    mins: "मिनट",
    queuePosition: "कतार की स्थिति",
    away: "दूर",
    timingsTitle: "दर्शन का समय",
    noticesTitle: "उत्सव सूचनाएँ",
    assistance: "सहायता की आवश्यकता है?",
    assistanceDesc: "हमारी समर्पित स्वयंसेवक टीम आपकी आध्यात्मिक यात्रा में आपकी सहायता के लिए यहाँ है।",

    // Committee Member
    committeeTitle: "समिति सदस्य डैशबोर्ड",
    totalToday: "आज कुल",
    currentlyInside: "वर्तमान में अंदर",
    avgWaitTime: "औसत प्रतीक्षा समय",
    currentlyServing: "वर्तमान सेवा",
    skip: "छोड़ें",
    nextToken: "अगला टोकन",
    pause: "रोकें",
    resume: "शुरू करें",
    vipPriorityPool: "वीआईपी प्राथमिकता सूची",
    waitlistItems: "प्रतीक्षा सूची आइटम",

    // Admin Dashboard
    welcomeAdmin: "स्वागत है एडमिन",
    liveSystemStatus: "लाइव सिस्टम स्थिति",
    totalBookingsToday: "आज की कुल बुकिंग",
    totalVisitorsToday: "आज के कुल आगंतुक",
    visitorsInside: "मंदिर के अंदर आगंतुक",
    queueCount: "कतार संख्या",
    vipVisitors: "आज वीआईपी आगंतुक",
    parkingOccupancy: "पार्किंग अधिभोग",
    completedDarshans: "पूरे हुए दर्शन",
    cancelledBookings: "रद्द बुकिंग",
    liveQueueOverview: "लाइव कतार विवरण",
    bookingAnalytics: "बुकिंग विश्लेषण",
    recentActivities: "हाल की गतिविधियाँ",
    upcomingFestival: "आगामी उत्सव",
    quickActions: "त्वरित कार्रवाई",
    notificationCenter: "सूचना केंद्र",
    capacityControls: "मंदिर क्षमता नियंत्रण",
    overrideLimit: "सीमा ओवरराइड करें",
    dailyVisitorLimit: "दैनिक आगंतुक सीमा",
    emergencyClosure: "आपातकालीन बंद प्रोटोकॉल",
    liftEmergency: "आपातकालीन बंद समाप्त करें",

    // Forms & Alerts
    nameLabel: "श्रद्धालु का नाम",
    categoryLabel: "श्रेणी",
    queueTypeLabel: "कतार प्रकार",
    saveChanges: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    confirmLogout: "क्या आप वाकई लॉगआउट करना चाहते हैं?",

    // Capacity Management
    capacityMgmtTitle: "क्षमता प्रबंधन",
    capacityMgmtSubtitle: "दैनिक बुकिंग सीमाओं, आगंतुक थ्रेशोल्ड और वास्तविक समय स्लॉट उपलब्धता का प्रबंधन करें।",
    exportReport: "रिपोर्ट निर्यात करें",
    totalDailyCapacity: "कुल दैनिक क्षमता",
    availableSlots: "उपलब्ध स्लॉट",
    capacityUtilization: "क्षमता का उपयोग",
    liveCapacityStatus: "लाइव क्षमता की स्थिति",
    onlineBooked: "ऑनलाइन बुक किया गया",
    walkins: "सीधे प्रवेश (Walk-ins)",
    online: "ऑनलाइन",
    cancelled: "रद्द",
    vipSpecial: "वीआईपी/विशेष",
    capacityConfiguration: "क्षमता विन्यास",
    maxVisitorsPerDay: "प्रति दिन अधिकतम आगंतुक",
    maxVehiclesPerDay: "प्रति दिन अधिकतम वाहन",
    maxPersonsPerBooking: "प्रति बुकिंग अधिकतम व्यक्ति",
    resetToDefaults: "डिफ़ॉल्ट पर रीसेट करें",
    currentStatus: "वर्तमान स्थिति",
    openForBooking: "बुकिंग के लिए खुला है",
    bookingsStopped: "बुकिंग रुकी हुई है",
    bookingRate: "बुकिंग दर",
    stop: "रोकें",
    systemAlerts: "सिस्टम अलर्ट",
    limitOverridden: "सीमा ओवरराइड करें",
    refreshingIn: "रीफ्रेशिंग",
    utilized: "उपयोग किया गया",

    // Parking Management
    parkingMgmtTitle: "पार्किंग प्रबंधन",
    parkingMgmtSubtitle: "वाहन पार्किंग, अधिभोग और आगंतुक वाहन रिकॉर्ड का प्रबंधन करें।",
    shiftMorning: "शिफ्ट: सुबह",
    totalCapacity: "कुल क्षमता",
    occupiedSlots: "भरे हुए स्लॉट",
    vehiclesToday: "आज के वाहन",
    vehicleEntryForm: "वाहन प्रवेश फॉर्म",
    vehicleNumber: "वाहन संख्या",
    vehicleType: "वाहन का प्रकार",
    twoWheeler: "दोपहिया",
    fourWheeler: "चौपहिया",
    bus: "बस",
    vip: "वीआईपी",
    driverName: "चालक का नाम",
    mobileNumber: "मोबाइल नंबर",
    tokenNumber: "टोकन संख्या",
    assignParkingSlot: "पार्किंग स्लॉट सौंपें",
    parkingSlotStatus: "पार्किंग स्लॉट की स्थिति",
    available: "उपलब्ध",
    occupied: "भरा हुआ",
    disabled: "विकलांग",
    quickSearch: "त्वरित खोज",
    markVehicleExit: "वाहन निकास चिह्नित करें",
    peakHourCapacity: "पीक ऑवर क्षमता",
    morningPeak: "सुबह (6AM - 10AM)",
    middayPeak: "दोपहर (11AM - 3PM)",
    eveningPeak: "शाम (4PM - 9PM)",
    recentVehicleEntries: "हाल के वाहन प्रवेश",
    viewAllEntries: "सभी प्रविष्टियां देखें",
    parked: "पार्क किया गया",
    exited: "बाहर निकला",

    // Scanner
    qrScannerTitle: "क्यूआर स्कैनर और आगंतुक सत्यापन",
    qrScannerSubtitle: "तत्काल दर्शन सत्यापन और वास्तविक समय प्रवेश ट्रैकिंग के लिए श्रद्धालु क्यूआर कोड स्कैन करें।",
    liveScanner: "लाइव स्कैनर",
    cameraActive: "कैमरा सक्रिय",
    scanQrCode: "क्यूआर कोड स्कैन करें",
    manualSearch: "मैन्युअल खोज",
    familyPass: "पारिवारिक पास",
    bookingTime: "बुकिंग का समय",
    phone: "फोन",
    vehicle: "वाहन",
    members: "सदस्य",
    gateNo: "गेट नंबर",
    verifyEntry: "प्रवेश सत्यापित करें",
    markInQueue: "कतार में चिह्नित करें",
    markEntered: "दर्शन पूर्ण हुआ",
    insideTemple: "मंदिर के अंदर",
    pending: "लंबित",
    recentScans: "हाल के स्कैन",
    viewAll: "सभी देखें",
    verified: "सत्यापित",
    waiting: "प्रतीक्षा कर रहा है",

    // Offline Verification
    offlineVerificationTitle: "ऑफ़लाइन आगंतुक सत्यापन",
    offlineVerificationSubtitle: "बिना ऑनलाइन बुकिंग के सीधे आने वाले श्रद्धालुओं का पंजीकरण और सत्यापन करें।",
    searchVisitor: "आगंतुक खोजें",
    mobileOrToken: "मोबाइल या टोकन नंबर",
    search: "खोजें",
    offlineVisitorForm: "ऑफ़लाइन आगंतुक प्रवेश फॉर्म",
    fullName: "पूरा नाम *",
    mobileNumberRequired: "मोबाइल नंबर *",
    placeVillage: "स्थान/शहर/गाँव",
    numberOfPersons: "व्यक्तियों की संख्या *",
    darshanDateLabel: "दर्शन तिथि",
    generateToken: "टोकन उत्पन्न करें",
    recentOfflineEntries: "हाल ही की ऑफ़लाइन प्रविष्टियां",
    visitorName: "आगंतुक का नाम",
    entryTime: "प्रवेश समय",
    currentGeneratedToken: "वर्तमान उत्पन्न टोकन",
    markEnteredTemple: "मंदिर में प्रवेश चिह्नित करें",
    printToken: "टोकन प्रिंट करें",
    dailyStatistics: "दैनिक सांख्यिकी",
    offlineVisitors: "ऑफ़लाइन आगंतुक",
    totalPersons: "कुल व्यक्ति",
    activeQueue: "सक्रिय कतार",
    completed: "पूरा हुआ",
    registrationConfirmed: "पंजीकरण की पुष्टि हो गई!",
    tokenId: "टोकन आईडी",
    printPass: "पास प्रिंट करें",
    downloadPass: "पास डाउनलोड करें",
    scanAtEntrance: "प्रवेश द्वार पर स्कैन करें",
    viewPassDetails: "पास विवरण देखें",
    generateNewEntry: "नई प्रविष्टि उत्पन्न करें",

    // Analytics
    analyticsTitle: "विश्लेषण और रिपोर्ट",
    analyticsSubtitle: "वास्तविक समय की जानकारी और श्रद्धालु यातायात प्रबंधन।",
    last24Hours: "पिछले 24 घंटे",
    dailyVisitorTrends: "दैनिक आगंतुक रुझान",
    crowdCapacity: "भीड़ की क्षमता",
    optimal: "इष्टतम",
    peopleOnsite: "साइट पर लोग",
    recommendedLimit: "अनुशंसित सीमा",
    vehicleEntry: "वाहन प्रवेश",
    twoWheelers: "दोपहिया वाहन",
    fourWheelers: "चौपहिया वाहन",
    largeVehicles: "बड़े वाहन",
    liveEntryCount: "लाइव प्रवेश संख्या",
    totalMale: "कुल पुरुष",
    totalFemale: "कुल महिला",
    avgDwellTime: "औसत निवास समय",
    slotManagement: "स्लॉट प्रबंधन",
    modifyVisitorLimits: "आगंतुक सीमाएं बदलें या आपातकालीन बंद करें।",
    emergencyClosureTitle: "आपातकालीन बंद",
    closureActive: "बंद सक्रिय है",
    auditLogs: "ऑडिट लॉग",
    viewAllActivity: "सभी गतिविधि देखें",
    hourlyEntryStats: "प्रति घंटा प्रवेश सांख्यिकी",
    table: "तालिका",
    heatmap: "हीटमैप",
    hourSlot: "घंटे का स्लॉट",
    totalVisitors: "कुल आगंतुक",
    vehicles: "वाहन",
    waitTime: "प्रतीक्षा समय"
  },
  mr: {
    // Navigation
    home: "मुख्य पृष्ठ",
    features: "वैशिष्ट्ये",
    queueStatus: "रांगेची स्थिती",
    contact: "संपर्क",
    login: "लॉगिन",
    logout: "लॉगआउट",
    dashboard: "डॅशबोर्ड",
    bookings: "बुकिंग्ज",
    vipManagement: "व्हीआयपी व्यवस्थापन",
    capacityManagement: "क्षमता व्यवस्थापन",
    staffManagement: "कर्मचारी व्यवस्थापन",
    settings: "सेटिंग्ज",
    help: "मदत",
    newEntry: "नवीन नोंदणी",
    qrScanner: "क्यूआर स्कॅनर",
    parkingManagement: "पार्किंग व्यवस्थापन",
    reportsAnalytics: "अहवाल आणि विश्लेषण",
    userManagement: "वापरकर्ता व्यवस्थापन",
    announcements: "घोषणा",
    festivalManagement: "उत्सव व्यवस्थापन",
    notifications: "सूचना",
    profile: "प्रोफाइल",
    myPass: "माझा पास",

    // Homepage
    heroTitle: "प्रतीक्षेशिवाय देवाचे दर्शन घ्या",
    heroSubtitle: "डिजिटल बुकिंग, क्यूआर पडताळणी आणि थेट रांग ट्रॅकिंगसह लांब रांगा टाळा. आमच्या आधुनिक प्रशासकीय तंत्रज्ञानासह सुलभ आध्यात्मिक प्रवासाचा अनुभव घ्या.",
    bookDarshan: "दर्शन बुक करा",
    checkQueue: "रांगेची स्थिती तपासा",
    featuresTitle: "सुव्यवस्थित मंदिर प्रवेश",
    featuresSub: "एकाच व्यावसायिक प्लॅटफॉर्मवर शांततापूर्ण आणि संघटित मंदिर दर्शनासाठी आवश्यक असलेल्या सर्व गोष्टी.",
    onlineBooking: "ऑनलाइन बुकिंग",
    onlineBookingDesc: "तुमच्या भेटीचे आधीच नियोजन करा आणि तुमच्या सोयीनुसार वेळ स्लॉट निवडा.",
    qrToken: "क्यूआर टोकन",
    qrTokenDesc: "जलद, संपर्कविरहित प्रवेशासाठी युनिक क्यूआर कोडसह त्वरित डिजिटल पास.",
    liveTracking: "थेट रांग ट्रॅकिंग",
    liveTrackingDesc: "तुमच्या मोबाईल डिव्हाइसवरून रिअल-टाइममध्ये प्रतीक्षा वेळ आणि रांगेतील स्थानाचे निरीक्षण करा.",
    vipMgt: "व्हीआयपी व्यवस्थापन",
    vipMgtDesc: "ज्येष्ठ नागरिक आणि दिव्यांग भाविकांसाठी विशेष जलद दर्शन व्यवस्था.",
    mobileFriendly: "मोबाईल अनुकूल",
    mobileFriendlyDesc: "सर्व स्मार्टफोन डिव्हाइसेसवर सहज प्रवेशासाठी डिझाइन केलेला रिस्पॉन्सिव्ह इंटरफेस.",
    realTimeUpdates: "रिअल-टाइम अपडेट्स",
    realTimeUpdatesDesc: "उत्सवाच्या वेळा आणि प्रशासकीय बदलांबद्दल एसएमएस आणि ॲप अलर्ट मिळवा.",
    announcementsTitle: "घोषणा आणि सूचना",
    officialPortal: "अधिकृत स्मार्ट दर्शन पोर्टल",
    verifyAtGate: "प्रवेशद्वारावर पडताळणी करा",
    slot: "वेळ स्लॉट",
    noticeBoard: "मंदिर सूचना फलक",
    noticeSubtitle: "नवीनतम सणांचे वेळापत्रक आणि प्रशासकीय घोषणांसह अपडेट रहा.",
    viewAllNotices: "सर्व सूचना पहा",
    readDetails: "तपशील वाचा",
    watchLive: "थेट पहा",
    donateNow: "आता दान करा",
    newTag: "नवीन",
    updateTag: "अपडेट",
    adminTag: "प्रशासन",
    notice1Title: "महाशिवरात्री विशेष वेळ",
    notice1Desc: "विशेष प्रार्थना आणि अभिषेक सोहळ्यासाठी मंदिर रात्रभर उघडे राहील.",
    notice2Title: "सकाळच्या आरतीचे थेट प्रक्षेपण",
    notice2Desc: "घरी बसून दिव्य ऊर्जेचा अनुभव घ्या. आमच्या पोर्टलवर दररोज पहाटे ५:३० वाजता थेट प्रक्षेपण सुरू होते.",
    notice3Title: "अन्नदान देणगी पोर्टल",
    notice3Desc: "आम्ही भाविकांसाठी जेवण प्रायोजित करण्यासाठी एक सरलीकृत पोर्टल सुरू केले आहे. आता योगदान द्या.",

    // User Dashboard
    welcomeUser: "परत आल्याबद्दल स्वागत",
    darshanDate: "दर्शनाची तारीख: 24 ऑक्टोबर, 2026",
    currentStatus: "सध्याची स्थिती: निश्चित",
    digitalPass: "डिजिटल दर्शन पास",
    devoteeName: "भाविकाचे नाव",
    tokenId: "टोकन आयडी",
    mobile: "मोबाईल",
    persons: "व्यक्ती",
    reportingTime: "रिपोर्टिंग वेळ",
    viewPass: "पास पहा",
    downloadPass: "पास डाउनलोड करा",
    entranceGate: "प्रवेश द्वार ३ वर स्कॅन करा",
    liveQueue: "थेट रांग",
    currentToken: "सध्याचा टोकन",
    yourToken: "तुमचा टोकन",
    queueProgress: "रांगेची प्रगती",
    complete: "पूर्ण",
    estWait: "अंदाजे वेळ",
    mins: "मिनिटे",
    queuePosition: "रांगेतील स्थान",
    away: "लांब",
    timingsTitle: "दर्शनाची वेळ",
    noticesTitle: "उत्सव सूचना",
    assistance: "मदत हवी आहे का?",
    assistanceDesc: "आमची समर्पित स्वयंसेवक टीम तुमच्या आध्यात्मिक प्रवासात मदत करण्यासाठी येथे आहे.",

    // Committee Member
    committeeTitle: "समिती सदस्य डॅशबोर्ड",
    totalToday: "आज एकूण",
    currentlyInside: "सध्या आत असलेले",
    avgWaitTime: "सरासरी प्रतीक्षा वेळ",
    currentlyServing: "सध्याचे सेवा टोकन",
    skip: "पुढचे",
    nextToken: "पुढील टोकन",
    pause: "थांबवा",
    resume: "सुरू करा",
    vipPriorityPool: "व्हीआयपी प्राधान्य सूची",
    waitlistItems: "प्रतीक्षा सूचीमधील भाविक",

    // Admin Dashboard
    welcomeAdmin: "स्वागत आहे ॲडमीन",
    liveSystemStatus: "थेट प्रणाली स्थिती",
    totalBookingsToday: "आजच्या एकूण बुकिंग्ज",
    totalVisitorsToday: "आजचे एकूण भाविक",
    visitorsInside: "मंदिरातील सध्याचे भाविक",
    queueCount: "रांगेतील संख्या",
    vipVisitors: "आजचे व्हीआयपी भाविक",
    parkingOccupancy: "पार्किंगची स्थिती",
    completedDarshans: "पूर्ण झालेली दर्शने",
    cancelledBookings: "रद्द केलेल्या बुकिंग्ज",
    liveQueueOverview: "थेट रांग आढावा",
    bookingAnalytics: "बुकिंग्जचे विश्लेषण",
    recentActivities: "सध्याच्या हालचाली",
    upcomingFestival: "येणारे सण/उत्सव",
    quickActions: "जलद कृती",
    notificationCenter: "सूचना केंद्र",
    capacityControls: "मंदिर क्षमता नियंत्रणे",
    overrideLimit: "मर्यादा बदला",
    dailyVisitorLimit: "दैनिक भाविक मर्यादा",
    emergencyClosure: "आणीबाणी बंद प्रोटोकॉल",
    liftEmergency: "आणीबाणी बंद मागे घ्या",

    // Forms & Alerts
    nameLabel: "भाविकाचे नाव",
    categoryLabel: "वर्ग",
    queueTypeLabel: "रांगेचा प्रकार",
    saveChanges: "बदल जतन करा",
    cancel: "रद्द करा",
    confirmLogout: "तुम्हाला खरोखर लॉगआउट करायचे आहे का?",

    // Capacity Management
    capacityMgmtTitle: "क्षमता व्यवस्थापन",
    capacityMgmtSubtitle: "दैनिक बुकिंग मर्यादा, भाविक मर्यादा आणि रिअल-टाइम स्लॉट उपलब्धतेचे व्यवस्थापन करा.",
    exportReport: "अहवाल निर्यात करा",
    totalDailyCapacity: "एकूण दैनिक क्षमता",
    availableSlots: "उपलब्ध स्लॉट",
    capacityUtilization: "क्षमतेचा वापर",
    liveCapacityStatus: "थ्रेट क्षमता स्थिती",
    onlineBooked: "ऑनलाइन बुक केलेले",
    walkins: "थेट प्रवेश (Walk-ins)",
    online: "ऑनलाइन",
    cancelled: "रद्द",
    vipSpecial: "व्हीआयपी/विशेष",
    capacityConfiguration: "क्षमता कॉन्फिगरेशन",
    maxVisitorsPerDay: "दररोज जास्तीत जास्त भाविक",
    maxVehiclesPerDay: "दररोज जास्तीत जास्त वाहने",
    maxPersonsPerBooking: "प्रति बुकिंग जास्तीत जास्त व्यक्ती",
    resetToDefaults: "डिफॉल्टवर रीसेट करा",
    currentStatus: "सध्याची स्थिती",
    openForBooking: "बुकिंगसाठी खुले",
    bookingsStopped: "बुकिंग थांबवले",
    bookingRate: "बुकिंग दर",
    stop: "थांबवा",
    systemAlerts: "प्रणाली अलर्ट",
    limitOverridden: "मर्यादा बदला",
    refreshingIn: "रीफ्रेश होत आहे",
    utilized: "वापरलेले",

    // Parking Management
    parkingMgmtTitle: "पार्किंग व्यवस्थापन",
    parkingMgmtSubtitle: "वाहन पार्किंग, पार्किंगची स्थिती आणि भाविक वाहन नोंदींचे व्यवस्थापन करा.",
    shiftMorning: "शिफ्ट: सकाळ",
    totalCapacity: "एकूण क्षमता",
    occupiedSlots: "भरलेले स्लॉट",
    vehiclesToday: "आजची वाहने",
    vehicleEntryForm: "वाहन प्रवेश फॉर्म",
    vehicleNumber: "वाहन क्रमांक",
    vehicleType: "वाहनाचा प्रकार",
    twoWheeler: "दुचाकी",
    fourWheeler: "चारचाकी",
    bus: "बस",
    vip: "व्हीआयपी",
    driverName: "चालकाचे नाव",
    mobileNumber: "मोबाईल क्रमांक",
    tokenNumber: "टोकन क्रमांक",
    assignParkingSlot: "पार्किंग स्लॉट द्या",
    parkingSlotStatus: "पार्किंग स्लॉटची स्थिती",
    available: "उपलब्ध",
    occupied: "भरलेले",
    disabled: "अपंग",
    quickSearch: "जलद शोध",
    markVehicleExit: "वाहन बाहेर पडल्याचे नोंदवा",
    peakHourCapacity: "गर्दीच्या वेळेची क्षमता",
    morningPeak: "सकाळ (6AM - 10AM)",
    middayPeak: "दुपार (11AM - 3PM)",
    eveningPeak: "संध्याकाळ (4PM - 9PM)",
    recentVehicleEntries: "अलीकडील वाहन प्रवेश",
    viewAllEntries: "सर्व नोंदी पहा",
    parked: "पार्क केलेले",
    exited: "बाहेर पडले",

    // Scanner
    qrScannerTitle: "क्यूआर स्कॅनर आणि भाविक पडताळणी",
    qrScannerSubtitle: "झटपट दर्शन पडताळणी आणि रिअल-टाइम प्रवेश ट्रॅकिंगसाठी भाविकांचे क्यूआर कोड स्कॅन करा.",
    liveScanner: "थेट स्कॅनर",
    cameraActive: "कॅмера सक्रिय",
    scanQrCode: "क्यूआर कोड स्कैन करा",
    manualSearch: "मॅन्युअल शोध",
    familyPass: "कौटुंबिक पास",
    bookingTime: "बुकिंगची वेळ",
    phone: "फोन",
    vehicle: "वाहन",
    members: "सदस्य",
    gateNo: "गेट क्रमांक",
    verifyEntry: "प्रवेश पडताळा",
    markInQueue: "रांगेत असल्याचे नोंदवा",
    markEntered: "दर्शन पूर्ण झाले",
    insideTemple: "मंदिराच्या आत",
    pending: "प्रलंबित",
    recentScans: "अलीकडील स्कॅन",
    viewAll: "सर्व पहा",
    verified: "पडताळणी झाली",
    waiting: "प्रतीक्षेत",

    // Offline Verification
    offlineVerificationTitle: "ऑफ़लाइन भाविक पडताळणी",
    offlineVerificationSubtitle: "ऑनलाइन बुकिंग नसलेल्या थेट येणाऱ्या भाविकांची नोंदणी आणि पडताळणी करा.",
    searchVisitor: "भाविक शोधा",
    mobileOrToken: "मोबाईल किंवा टोकन क्रमांक",
    search: "शोधा",
    offlineVisitorForm: "ऑफ़लाइन भाविक नोंदणी फॉर्म",
    fullName: "पूर्ण नाव *",
    mobileNumberRequired: "मोबाईल क्रमांक *",
    placeVillage: "ठिकाण/शहर/गाव",
    numberOfPersons: "व्यक्तींची संख्या *",
    darshanDateLabel: "दर्शनाची तारीख",
    generateToken: "टोकन तयार करा",
    recentOfflineEntries: "अलीकडील ऑफलाइन नोंदी",
    visitorName: "भाविकाचे नाव",
    entryTime: "प्रवेशाची वेळ",
    currentGeneratedToken: "सध्याचा तयार झालेला टोकन",
    markEnteredTemple: "प्रवेश केल्याचे नोंदवा",
    printToken: "टोकन प्रिंट करा",
    dailyStatistics: "दैनिक आकडेवारी",
    offlineVisitors: "ऑफलाइन भाविक",
    totalPersons: "एकूण व्यक्ती",
    activeQueue: "सक्रिय रांग",
    completed: "पूर्ण झाले",
    registrationConfirmed: "नोंदणी निश्चित झाली!",
    tokenId: "टोकन आयडी",
    printPass: "पास प्रिंट करा",
    downloadPass: "पास डाउनलोड करा",
    scanAtEntrance: "प्रवेशद्वारावर स्कॅन करा",
    viewPassDetails: "पास तपशील पहा",
    generateNewEntry: "नवीन नोंदणी करा",

    // Analytics
    analyticsTitle: "विश्लेषण आणि अहवाल",
    analyticsSubtitle: "रिअल-टाइम आकडेवारी आणि भाविक रहदारी व्यवस्थापन.",
    last24Hours: "गेले २४ तास",
    dailyVisitorTrends: "दैनिक भाविक कल",
    crowdCapacity: "गर्दीची क्षमता",
    optimal: "योग्य",
    peopleOnsite: "मंदिरातील लोक",
    recommendedLimit: "शिफारस केलेली मर्यादा",
    vehicleEntry: "वाहन प्रवेश",
    twoWheelers: "दुचाकी वाहने",
    fourWheelers: "चारचाकी वाहने",
    largeVehicles: "मोठी वाहने",
    liveEntryCount: "थेट प्रवेश संख्या",
    totalMale: "एकूण पुरुष",
    totalFemale: "एकूण महिला",
    avgDwellTime: "सरासरी वास्तव्य वेळ",
    slotManagement: "स्लॉट व्यवस्थापन",
    modifyVisitorLimits: "भाविक मर्यादा बदला किंवा आपत्कालीन बंद करा.",
    emergencyClosureTitle: "आपत्कालीन बंद",
    closureActive: "बंद सक्रिय आहे",
    auditLogs: "ऑडिट लॉग",
    viewAllActivity: "सर्व हालचाली पहा",
    hourlyEntryStats: "तासाची प्रवेश आकडेवारी",
    table: "तासिका",
    heatmap: "हीटमॅप",
    hourSlot: "वेळेचा स्लॉट",
    totalVisitors: "एकूण भाविक",
    vehicles: "वाहने",
    waitTime: "प्रतीक्षा वेळ"
  }
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  const setLanguage = (lang) => {
    setCurrentLanguage(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
